services:
  - type: web
    name: center-of-excellence
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: DISABLE_HTTPS_REDIRECT
        value: "true"
